app:
  name: 'course_project'
  version: 'v0.1'

logger:
  level: 'info'
  file: 'logs.log'

jwt:
  jwt_key: '13278sabdjkas1289'

http:
  port: 8081

database:
  driver: 'postgres'
  host: 'localhost'
  port: 5432
  user: 'user'
  password: 'pass'
  dbname: 'salads'